.PHONY: build-template start-webhook-server stop-worker

build-template:
	npm --prefix .. run build-template

start-webhook-server:
	npm --prefix .. run start-webhook-server

stop-worker:
	npm --prefix .. run stop-worker -- $(SANDBOX_ID)
