.PHONY: build-template show-environment start-app-webhook-server stop-worker

build-template:
	npm --prefix .. run build-template

show-environment:
	npm --prefix .. run show-environment

start-app-webhook-server:
	npm --prefix .. run start-app-webhook-server

stop-worker:
	npm --prefix .. run stop-worker -- $(SANDBOX_ID)
