/**
 * Example 1 -- the simplest path through the system.
 *
 * Generate a Playwright test from a one-line natural-language spec
 * and run it once in a fresh E2B sandbox. No healing.
 *
 * Run:  pnpm tsx examples/01-basic-test.ts
 */

import 'dotenv/config';

import { route } from '../src/router.js';
import { runInSandbox } from '../src/runner.js';
import type { GeneratedTest, TestSpec } from '../src/types.js';

const spec: TestSpec = {
  url: 'https://e2b.dev',
  description:
    'The page should mention "AI agents" somewhere on it within 10 seconds of loading.',
};

const PROMPT = `You are an expert Playwright test author.
Output a single TypeScript file -- no markdown fences, no commentary.
Use @playwright/test, import { test, expect }.

Spec:
URL: ${spec.url}
What to verify: ${spec.description}

Return only the TypeScript file content.`;

async function main(): Promise<void> {
  console.log('→ generating test...');
  const { text, provider } = await route(PROMPT);
  const generated: GeneratedTest = { code: text.trim(), provider };
  console.log(`✓ generated by ${provider} (${generated.code.length} chars)`);

  console.log('→ running in E2B playwright-chromium sandbox (~30-50s)...');
  const result = await runInSandbox(generated);
  console.log(result.passed ? '✓ test passed' : '✗ test failed');
  if (!result.passed) {
    console.log('--- stdout ---');
    console.log(result.stdout);
    console.log('--- stderr ---');
    console.log(result.stderr);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
