/**
 * Example 2 -- the headline example.
 *
 * Run a test that is *deliberately likely to fail on the first try*
 * (description is vague enough that the LLM may pick brittle selectors).
 * The healing loop kicks in: failure stdout + a captured page snapshot
 * are fed back into the LLM, which rewrites the test with more robust
 * selectors. We retry up to HEAL_MAX_ATTEMPTS times.
 *
 * This is the qualitymax.io self-healing pattern, ported to E2B.
 *
 * Run:  pnpm tsx examples/02-self-healing.ts
 */

import 'dotenv/config';

import { runHealingTest } from '../src/healer.js';
import type { TestSpec } from '../src/types.js';

const spec: TestSpec = {
  url: 'https://e2b.dev',
  description:
    'Click whatever link or button appears to lead to the documentation, ' +
    'then verify the destination page contains the word "sandbox".',
  context:
    'The site nav may have changed since the LLM was trained. Prefer ' +
    'role / accessible-name / data-testid based selectors.',
};

async function main(): Promise<void> {
  const trace = await runHealingTest(spec, 3);

  console.log(`\nFinal: ${trace.finalPassed ? '✓ passed' : '✗ failed'}`);
  console.log(`Attempts: ${trace.attempts.length}`);

  trace.attempts.forEach((a) => {
    console.log(
      `  attempt ${a.attempt} -- ${a.result.passed ? 'pass' : 'fail'} ` +
        `(generated by ${a.generated.provider})`,
    );
  });

  if (!trace.finalPassed) {
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
