[project]
name = "e2b-hello-world"
version = "0.1.0"
description = "Hello world example for E2B"
authors = [{ name = "Vasek Mlejnsky", email = "vasek@e2b.dev" }]
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "e2b-code-interpreter>=2.9.0,<3",
    "e2b>=2.39,<3",
    "python-dotenv>=1.0.1,<2",
]

[project.scripts]
start = "e2b_hello_world.main:main"

[tool.hatch.build.targets.wheel]
packages = ["e2b_hello_world"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
